### ISSUE TITLE
Stats Sprint Length label cut off when sprint length = 1 minute

### ISSUE THREAD

**Issue by MalignantCarp** [kinabalu/obsidian-word-sprint#14]
This issue occurs when you have a sprint length of 1 minute:

![image](https://user-images.githubusercontent.com/93364935/139567616-a062f11f-f91a-4074-b111-f55f2a244d3b.png)

In utils.ts, the secondsToHumanize function will return an empty string if seconds = 60. The seconds > 60 statement won't fire and and the seconds % 60 > 0 will not fire either because 60 % 60 = 0.

**Comment by kinabalu** [comment]
fix is ready and will be released along with 0.0.16
