### ISSUE TITLE
Toggle to hide STATUS and time left text

### ISSUE THREAD

**Issue by SlRvb** [kinabalu/obsidian-word-sprint#16]
Can there be a toggle in the plugin to either keep or remove the `left` and `STATUS` from the side panel?

It seems just a little redundant to me and it takes up a bit more space than I'd like. A toggle to keep it on or off for those that would want to keep it and those that don't would be ideal.

I think it looks a bit cleaner without them:
![hqT1wIXWNz](https://user-images.githubusercontent.com/54087190/139570240-de3ceca3-864a-4c84-97b5-24d30be22e2e.png)

**Comment by kinabalu** [comment]
fixed in 0.0.17
