### ISSUE TITLE
When writing for less than a minute, the average words per minute is a divide by zero

### ISSUE THREAD

**Issue by kinabalu** [kinabalu/obsidian-word-sprint#21]

**Comment by MalignantCarp** [comment]
Unless I've complete lost it, changing the averageWordsPerMinute calculation to this ought to solve it for all cases where elapsedMilliseconds is not 0:

```averageWordsPerMinute: this.getWordCountDisplay() * 1000 * 60 / Math.floor(this.elapsedMilliseconds)```

**Comment by kinabalu** [comment]
fixed in 0.0.20
