### ISSUE TITLE
Feature Request: Track total sprint count

### ISSUE THREAD

**Issue by leethobbit** [kinabalu/obsidian-word-sprint#23]
Hey there, I absolutely love v0.1.1!  It's been fantastic.  But as I was looking at the UI, I noticed there's a space between Daily Word Count and the View Stats button and I had a thought - Could we add "Total Sprints: " in that space?  it would be nice to know how many I end up doing throughout a given project or for NaNo, and we could use this to calc other metrics on our own, such as average words per sprint which are really useful for figuring out how much time is needed per day to meet our longterm goals.

Ideally, this would come with a reset option in the plugin settings like Daily and Total Word Counts do so we can keep them all in sync.

Thanks so much!

**Comment by kinabalu** [comment]
This exists now, so closing this.
