### ISSUE TITLE
[Bug] Changing Time On Leaf Reverts Back On Start

### ISSUE THREAD

**Issue by SlRvb** [kinabalu/obsidian-word-sprint#42]
Clicking on the time on the leaf and changing the time reverts back to the default whenever I press the start button.

![KxDQDcbfT5](https://user-images.githubusercontent.com/54087190/141697232-345c380b-3130-43c9-893c-d42705e6b138.gif)

**Comment by MalignantCarp** [comment]
I have created a pull request that fixes this issue.

**Comment by kinabalu** [comment]
closing this as that PR likely fixed it.
