### ISSUE TITLE
Bug/feature missing? caching the last nanowrimo project and challenge

### ISSUE THREAD

**Issue by Rhydderch** [kinabalu/obsidian-word-sprint#46]
Hi again!

This morning I had wifi connection issues. This helped me notice that my projects and challenges were gone from the settings tab.
![image](https://user-images.githubusercontent.com/3197629/147071419-11f0132a-bc4e-44b6-9ab2-077b281bbf6b.png)
Would it be possible to "cache" the projects & challenges so that we can select them even offline?

**Comment by kinabalu** [comment]
if you're not online, the tracking data for NanoWriMo will not be uploaded... is the intent here just to ensure that it shows this in your Sprint leaf?

**Comment by kinabalu** [comment]
It's been 4+ months. Please re-open if you want us to look into this further.
