### ISSUE TITLE
Bug: Can't set a custom timer

### ISSUE THREAD

**Issue by icegrim** [kinabalu/obsidian-word-sprint#48]
I can't set custom counter after last update (0.14.2). The default timer I have chosen is 50 minutes, but when I want to do a short sprint of 10 minutes, it starts again at 50 minutes.

**Comment by kinabalu** [comment]
just getting back to some testing, not sure what version you were running before but testing with latest version of Obsidian and the Word Sprint tool this correctly changes the sprint to 10 minutes for that single run, and then swaps back to 50. Please reopen if you find issues.
