### ISSUE TITLE
0.2.7 doesn’t load on ipad

### ISSUE THREAD

**Issue by Azmoinal** [kinabalu/obsidian-word-sprint#54]
After the upgrade to the latest version, Word Sprint has been disabled on my iPad and it fails to load. Is it an intended change?

**Comment by kinabalu** [comment]
No, not intended at all. Doesn't appear to load on iOS at all. Works on desktop so far.

**Comment by kinabalu** [comment]
0.2.9 has a fix for iOS now -- apologies the build chain changed and I wasn't aware of it including something that doesn't work on mobile. Thanks for reporting!
