### ISSUE TITLE
Customize warning notice timers

### ISSUE THREAD

**Issue by MalignantCarp** [kinabalu/obsidian-word-sprint#7]
Users should be able to set a custom length for each warning timer to something suitable for them. I suspect the only constraint necessary is that the second notice must be longer than the first.

To eliminate that validation requirement, the alternative would be to set the second warning to be time after the first warning. For example, to have the timer fire at 10 seconds and then 60 seconds after you stop writing, you would select 10 and 50 seconds, respectively. The first warning would fire at 10 seconds and then the second warning 50 seconds after the first warning.

**Comment by kinabalu** [comment]
will be available in 0.0.10
