### ISSUE TITLE
Feature Request: Word Count "Trip Meter"

### ISSUE THREAD

**Issue by leethobbit** [kinabalu/obsidian-word-sprint#9]
Now that we have that awesome leaf pane, I had a thought - It would be fantastic to have a word count "trip meter" that just continually adds up word counts across sprints.  Ideally, it would have a Reset button which would allow it to be used for easy daily word count goal tracking.

Optionally, a second trip meter that could be used for tracking longer term word counts (say, the 50k for NaNo or a project goal) would be wonderful.

The main issue I'm unsure about is this - Can the stats persist across closing/opening of Obsidian?  If not, then a single trip meter just for daily goals would still be really great.

Thanks!

**Comment by kinabalu** [comment]
we now have "stats" being persisted in an array which is also persisted to disk.
